### ISSUE TITLE
Bluetooth is broken

### ISSUE THREAD

**Issue by denysvitali** [linux-surface/surface-pro-x#47]
I don't know what happened since [the wiki article](https://github.com/linux-surface/surface-pro-x/wiki/Bluetooth) - but it looks like BT is broken.

```
$ sudo hciconfig
hci0:	Type: Primary  Bus: UART
	BD Address: 00:AA:BB:CC:DD:EE  ACL MTU: 0:0  SCO MTU: 0:0
	DOWN RAW
	RX bytes:381 acl:0 sco:0 events:53 errors:0
	TX bytes:240812 acl:0 sco:0 commands:977 errors:0
```

The BD Address in the original output is correct - I just masked it here.

The device shows up as an `hci0` device - but it's always down (and thus `bluetoothd` doesn't see the controller).
Trying to enable it results in an error (95):

```
$ sudo hciconfig hci0 up
Can't init device hci0: Operation not supported (95)
```

Debugging the driver it seems like the device is powered off just after the initialization:

```
[  334.543500] Bluetooth: HCI UART driver ver 2.3
[  334.543511] Bluetooth: HCI UART protocol H4 registered
[  334.543515] Bluetooth: HCI UART protocol BCSP registered
[  334.543609] Bluetooth: HCI UART protocol LL registered
[  334.543614] Bluetooth: HCI UART protocol ATH3K registered
[  334.543653] Bluetooth: HCI UART protocol Three-wire (H5) registered
[  334.544087] Bluetooth: HCI UART protocol Intel registered
[  334.544279] Bluetooth: HCI UART protocol Broadcom registered
[  334.544331] Bluetooth: HCI UART protocol QCA registered
[  334.544371] Bluetooth: HCI UART protocol Marvell registered
[  334.777635] Bluetooth: hci0: setting up wcn399x
[  334.910960] Bluetooth: hci0: QCA Product ID   :0x0000000a
[  334.910965] Bluetooth: hci0: QCA SOC Version  :0x40010224
[  334.910966] Bluetooth: hci0: QCA ROM Version  :0x00001001
[  334.910968] Bluetooth: hci0: QCA Patch Version:0x00006699
[  334.915948] Bluetooth: hci0: QCA controller version 0x02241001
[  334.915954] Bluetooth: hci0: QCA Downloading qca/crbtfw01.tlv
[  335.930053] Bluetooth: hci0: QCA Downloading qca/crnv01.bin
[  336.077731] Bluetooth: hci0: QCA setup on UART is completed
---

[  336.078001] hci0: type 1 len 3
[  336.078012] hu 000000007a695702 qca enq skb 00000000bc0c44a1 tx_ibs_state 0
[  336.078019] Device asleep, waking up and queueing packet

[  336.078138] hu 000000007a695702 wq awake device
[  336.078146] Vote serial clock true(true)
[  336.078151] hu 000000007a695702 send hci ibs cmd 0xfd



[  336.079023] hu 000000007a695702 recv hci ibs cmd 0xfc
[  336.079027] hu 000000007a695702 woke up



[  336.083429] hci0: type 1 len 3
[  336.083436] hu 000000007a695702 qca enq skb 00000000e79f3e09 tx_ibs_state 2
[  336.083442] Device awake, sending normally



[  336.083947] hci0: type 1 len 3
[  336.083953] hu 000000007a695702 qca enq skb 00000000e79f3e09 tx_ibs_state 2
[  336.083958] Device awake, sending normally



[  336.084285] hci0: type 1 len 4
[  336.084289] hu 000000007a695702 qca enq skb 00000000bc0c44a1 tx_ibs_state 2
[  336.084290] Device awake, sending normally



[  336.084975] hci0: type 1 len 5
[  336.084981] hu 000000007a695702 qca enq skb 0000000077d4293c tx_ibs_state 2
[  336.084987] Device awake, sending normally



[  336.085304] hci0: --- qca_power_off --
[  336.085312] hci0: type 1 len 3
[  336.085315] hu 000000007a695702 qca enq skb 0000000020f37c56 tx_ibs_state 2
[  336.085316] Device awake, sending normally



[  336.095716] hu 000000007a695702 qca flush
[  336.096051] hci0: sending power pulse c0 to controller


[  336.110658] hdev 0000000073c74723 serdev 0000000029b73abc
[  336.110670] hu 000000007a695702 qca flush
[  336.110677] hdev 0000000073c74723
[  336.110681] hdev 0000000073c74723 serdev 0000000029b73abc
[  336.110686] hu 000000007a695702 qca flush
[  338.104403] hu 000000007a695702 idle timeout in 2 state
[  338.104411] hu 000000007a695702 send hci ibs cmd 0xfe
[  338.104421] hu 000000007a695702 tx clock vote off
[  338.104425] Vote serial clock false(true)
```

(here the driver was compiled with `DEBUG=1`)

Does anyone know what's happening here?

**Comment by jglathe** [comment]
Hmm no idea. On the X13s and Volterra you need to set a MAC address, or BT won't come up. But there is one in hciconfig... although a dummy address.

**Comment by denysvitali** [comment]
I masked it, but it's the real one:

```
hci0:	Type: Primary  Bus: UART
	BD Address: 39:90:...
```

**Comment by jglathe** [comment]
bluetoothd doesn't come up without a BD address. Since you have one, that's not it. The log says its powering off in the end. Could this be a collision? Another BT host with the same address?

**Comment by denysvitali** [comment]
> Another BT host with the same address?

I don't think so...

I managed to get `hci0` up with a small trick:

```
sudo rmmod hci_uart && sleep 2 && sudo insmod hci_uart.ko && sudo hciconfig hci0 up
```

This then shows:

```
UP RUNNING RAW
```

when I start `hciconfig`.

Unfortunately I still can't do anything with bluez (`bluetoothctl`) as the controller doesn't show up.

**Comment by jglathe** [comment]
Actually I had quite a struggle to get BT up reliably on Volterra and X13s. The solution I use now is in [syshacks](https://github.com/jglathe/wdk2023_syshacks). It's two parts. 
One is to actually give a [default MAC address for the BT controller in the device tree](https://github.com/jglathe/linux_ms_dev_kit/commit/39564372cbb7c2b630b71cc306cf9bca49a6f18e), this helps for the hci0 to come up (it won't without one). 
Part two is using bootmac to set a unique MAC address, with vendor specific OUI. On these devices the actual MAC addresses are unknown or can't be read from the BIOS, so this is the hack.
`/var/spool/cron/crontabs/root` runs a delay (3 secs is sufficient here) and runs bootmac with parameters.
If you omit the delay it won't work (dunno why), if you try the same via systemd (with or without delay) it won't work (something with btmgt and ttys, weird, but effectively kills the use of btmgt with systemd). So the cron/bootmac approach has proven stable for now. 
All this started to re-appear with 6.6. I had it running "fine" with systemd and a simple set-script on 6.5.

**Comment by denysvitali** [comment]
OMG. 
Setting a bluetooth address (the way you did with `btmgmt public-addr 00:11:22:33:44:55` WORKED!

Thanks!!

**Comment by denysvitali** [comment]
It looks like the BT Address should be specified in the `local-bd-address` node property.

I'm pretty sure the same should be done for the Wi-Fi MAC Address (#45) and these should be patched somehow from the firmware tables (which should hold the value, apparently).

This would fix the issue as there will be no need of manually setting either the BT Addr or the Wi-Fi MAC Address.

**Comment by jglathe** [comment]
There are many questions arising. If the MAC adresses can be read from firmware tables (ACPI or UEFI) then it needs to be known for this model. The answer I got was "no" for the X13s, but they're on it. Meaning, it's on a long list of features / info they are trying to get from Lenovo / Qualcomm. Also, this new behaviour that the kernel insists on having a MAC address is not the best development, but they will have their reasons. Even setting local-bd-address appears to be not favored, I do it in my builds because it increases the chance of a usable bootup (although suboptimal as constant addresses are by nature). 
If you want at least "unique" addresses what many people and some distros seem to use as a workaround is bootmac which generates MACs from `/etc/machine-id`. Which does the job, quite nicely. If you have the full address (for example from Windows) you can set them completely (all 6 octets) in the `/var/spool/cron/crontabs/root` command. I only set the first three (desired OUI) and this is working nicely. "Unique", constant MAC addresses which don't fsck with BT registered devices, DHCP, other things that like constant MAC addresses.

**Comment by maxboone** [comment]
Thanks @jglathe and @denysvitali, just set this kernel up on my Pro X, setting the bluetooth address (even though one was showing up in hciconfig) in the device tree did wonders. Additionally, the messages for WiFi indeed show that that address is not read (properly) from system tables either:

```
ath10k_snoc 18800000.wifi: invalid MAC address; choosing random
```

If it weren't for this issue it would've been a real pickle to figure out!
